### ISSUE TITLE
How Can I use CrispyDB

### ISSUE THREAD

**Issue by ArnavVashisthCodingAccountnew** [Amazeryogo/CrispyDB#1]
Dear Suvid Datta,
I am a fellow developer who uses HTML,CSS JS & a no code platform , Thunkable. How can I use this app in my websites and thunkapps?

I await Your Reply!

Kind Regards,
Arnav Vashisth,
Winner Of CodingBee

**Comment by ArnavVashisthCodingAccountnew** [comment]
Waiting

**Comment by Amazeryogo** [comment]
Hello Arnav Vashisth,

Right now, It technically works, but i wont consider it ready yet ( considering how recently i started the project). It can the run basic tasks of reading and writing.

To get started, You need to have atleast python 3.9.7 (you can change the version in config/config.json). Set the path of the folder you want to use to keep all of the data of the database (personally i use the DB folder and my path is kept as /home/suvid/Projects/CrispyDB/DB on my local computer) 

Now run the main.py file, it should start running a basic flask app
(note that you do need to install flask and flask_limiter)

To test out the server, you can use the python scripts in the testing folder, or you could write your own.

right now, you can only create a collection, load a collection, save an object, remove an object and delete a collection.

(Collections are basically a glorified json file to store and retrive some json.)

I plan to add more features so dont use it in a project right now.

Thanks,
Suvid

PS- congrats on winning the codingbee

**Comment by ArnavVashisthCodingAccountnew** [comment]
Good @amazeryogo !
Looking forward to trying this DB out whenever I start learning the snake,
Python.

**Comment by ArnavVashisthCodingAccountnew** [comment]
Thank You

**Comment by Amazeryogo** [comment]
no problem

**Comment by ArnavVashisthCodingAccountnew** [comment]
I will be there tomorrow
